config:
  softwareConfig:
    airflowConfigOverrides:
      core-dag_concurrency: "16"
  airflowByoidUri: https://775dd43b57bb42bb9c24c3749ca57033-dot-us-central1.composer.byoid.googleusercontent.com
  airflowUri: https://775dd43b57bb42bb9c24c3749ca57033-dot-us-central1.composer.googleusercontent.com
  dagGcsPrefix: gs://us-central1-avito-cloud-com-85efc29c-bucket/dags
  dataRetentionConfig:
    airflowMetadataRetentionConfig:
      retentionMode: RETENTION_MODE_DISABLED
  encryptionConfig: {}
  environmentSize: ENVIRONMENT_SIZE_SMALL
  nodeConfig:
    composerInternalIpv4CidrBlock: 100.64.128.0/20
    ipAllocationPolicy: {}
    serviceAccount: 674629315151-compute@developer.gserviceaccount.com
  privateEnvironmentConfig: {}
  softwareConfig:
    cloudDataLineageIntegration: {}
    imageVersion: composer-3-airflow-2.10.2-build.9
    pypiPackages:
      apache-airflow-providers-google: ==10.13.1
      pandas: ''
      pyarrow: ''
    webServerPluginsMode: PLUGINS_ENABLED
  webServerNetworkAccessControl:
    allowedIpRanges:
    - description: Allows access from all IPv4 addresses (default value)
      value: 0.0.0.0/0
    - description: Allows access from all IPv6 addresses (default value)
      value: ::0/0
  workloadsConfig:
    dagProcessor:
      count: 1
      cpu: 1.0
      memoryGb: 4.0
      storageGb: 1.0
    scheduler:
      count: 1
      cpu: 0.5
      memoryGb: 2.0
      storageGb: 1.0
    triggerer:
      count: 1
      cpu: 0.5
      memoryGb: 1.0
    webServer:
      cpu: 0.5
      memoryGb: 2.0
      storageGb: 1.0
    worker:
      cpu: 0.5
      maxCount: 3
      memoryGb: 2.0
      minCount: 1
      storageGb: 10.0
createTime: '2025-03-11T05:56:05.951408Z'
labels:
  force-restart: 'true'
  restart: 'true'
name: projects/ordinal-reason-449406-f0/locations/us-central1/environments/avito-cloud-composer
state: RUNNING
storageConfig:
  bucket: us-central1-avito-cloud-com-85efc29c-bucket
updateTime: '2025-03-11T09:12:12.054127Z'
uuid: 775dd43b-57bb-42bb-9c24-c3749ca57033

  
config:
  airflowByoidUri: https://e940790d81604bf3be4ffeaaf3e5b1fb-dot-us-central1.composer.byoid.googleusercontent.com
  airflowUri: https://e940790d81604bf3be4ffeaaf3e5b1fb-dot-us-central1.composer.googleusercontent.com
  dagGcsPrefix: gs://us-central1-avito-cloud-com-4bd2c0db-bucket/dags
  dataRetentionConfig:
    airflowMetadataRetentionConfig:
      retentionMode: RETENTION_MODE_DISABLED
  encryptionConfig: {}
  environmentSize: ENVIRONMENT_SIZE_SMALL
  nodeConfig:
    composerInternalIpv4CidrBlock: 100.64.128.0/20
    ipAllocationPolicy: {}
    serviceAccount: 674629315151-compute@developer.gserviceaccount.com
  privateEnvironmentConfig: {}
  softwareConfig:
    airflowConfigOverrides:
      core-dag_concurrency: '16'
    cloudDataLineageIntegration: {}
    imageVersion: composer-3-airflow-2.10.2-build.9
    webServerPluginsMode: PLUGINS_ENABLED
  webServerNetworkAccessControl:
    allowedIpRanges:
    - description: Allows access from all IPv4 addresses (default value)
      value: 0.0.0.0/0
    - description: Allows access from all IPv6 addresses (default value)
      value: ::0/0
  workloadsConfig:
    dagProcessor:
      count: 1
      cpu: 1.0
      memoryGb: 4.0
      storageGb: 1.0
    scheduler:
      count: 1
      cpu: 0.5
      memoryGb: 2.0
      storageGb: 1.0
    triggerer:
      count: 1
      cpu: 0.5
      memoryGb: 1.0
    webServer:
      cpu: 0.5
      memoryGb: 2.0
      storageGb: 1.0
    worker:
      cpu: 0.5
      maxCount: 3
      memoryGb: 2.0
      minCount: 1
      storageGb: 10.0
createTime: '2025-03-11T09:56:32.368603Z'
name: projects/ordinal-reason-449406-f0/locations/us-central1/environments/avito-cloud-composer
state: RUNNING
storageConfig:
  bucket: us-central1-avito-cloud-com-4bd2c0db-bucket
updateTime: '2025-03-11T10:16:38.469259Z'
uuid: e940790d-8160-4bf3-be4f-feaaf3e5b1fb
